# Generated by Django 5.0.7 on 2024-11-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('localizacao', models.CharField(max_length=100)),
                ('times_participantes', models.ManyToManyField(related_name='campeonatos', to='equipes.equipes')),
            ],
        ),
    ]
