# Generated by Django 5.0.7 on 2024-11-06 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
        ('torneios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('localizacao', models.CharField(max_length=100)),
                ('gols_Equipe_casa', models.IntegerField(default=0)),
                ('gols_Equipe_visitante', models.IntegerField(default=0)),
                ('Equipe_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='equipes.equipes')),
                ('Equipe_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='equipes.equipes')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneios.torneios')),
            ],
        ),
    ]
