# Generated by Django 5.0.7 on 2024-11-06 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=50)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('posicao', models.CharField(choices=[('atacante', 'Atacante'), ('meio_campo', 'Meio Campo'), ('defensor', 'Defensor'), ('goleiro', 'Goleiro')], max_length=50)),
                ('pe_preferido', models.CharField(choices=[('destro', 'Destro'), ('canhoto', 'Canhoto'), ('ambidestro', 'Ambidestro')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jogadores', to='equipes.equipes')),
            ],
        ),
    ]
