# Generated by Django 5.0.7 on 2024-11-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
