# Generated by Django 5.1.3 on 2024-11-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipes',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipes',
            name='fundacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipes',
            name='treinador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
