# Generated by Django 5.0.7 on 2024-11-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipes', '0002_alter_equipes_cidade_alter_equipes_fundacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipes',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='equipes/logos/'),
        ),
    ]
